// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Jason Roughley <pis.controller@gmail.com>

#pragma once

#include "JPCsvImporter.h"

inline namespace jf {

// OpenPnP's Altium CSV importer: named columns, by the names Altium's
// pick and place export gives them.
class JPAltiumCsvImporter : public JPCsvImporter {
public:
    std::string name() const override { return "Altium .csv"; }
    std::string description() const override { return "Import Named Comma Separated Values Files generated by Altium."; }
    Patterns patterns() const override;
};

} // inline namespace jf
