// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Jason Roughley <pis.controller@gmail.com>

#pragma once

#include "JPBoardImporter.h"

inline namespace jf {

// The files EAGLE's mountsmd.ulp writes (.mnt for the top, .mnb for the
// bottom), as OpenPnP's EagleMountsmdUlpImporter reads them: "Name X Y
// Angle Value Package" in mm. A part is "Package-Value" (the value taken as
// the package when there is no package), assigned (and made when missing)
// only when asked.
class JPEagleMountsmdUlpImporter : public JPBoardImporter {
public:
    std::string name() const override { return "EAGLE mountsmd.ulp"; }
    std::string description() const override { return "Import files generated by EAGLE's mountsmd.ulp."; }
    std::vector<File> files() const override {
        return { { "Top File (.mnt)", { "mnt" } }, { "Bottom File (.mnb)", { "mnb" } } };
    }
    std::vector<Option> options() const override { return { { "Create Missing Parts", "", true } }; }

protected:
    void parse(const std::vector<std::string>& files, const std::vector<bool>& options, JPConfiguration& config,
               JPBoard& out) const override;

private:
    static void parseFile(const std::string& path, JPSide side, bool createMissingParts, JPConfiguration& config,
                          JPBoard& out);
};

} // inline namespace jf
