// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Jason Roughley <pis.controller@gmail.com>

// OpenPnP's TavellingSalesmanTest: places like a pick and place machine's (some strewn at random, rows of feeders
// along X and along Y, a little Z), generated by Java's Random(42) as OpenPnP's test does, routed from the origin
// across (no end), round a loop (back to the origin) and to (1000, 500), with the travel cost of the test machine's
// camera axes (OpenPnP's migration default: 250 mm/s; the acceleration A slow, B fast on X, C fast on both), 610,
// 70 and 16 places. The route's straight-line length must be within 1% of OpenPnP's own.
// Tests check with assert(); a Release build must not compile it away.
#undef NDEBUG
#include <cassert>
#include <cmath>
#include <cstdio>
#include <vector>

#include "common/JPJavaRandom.h"
#include "tasks/JPTravel.h"

using namespace jf;

namespace {

JPLocation mm(double x, double y, double z) { return JPLocation(JPLengthUnit::Millimeters, x, y, z, 0); }

void test(const char* name, double xAcceleration, double yAcceleration, const double targets[3]) {
    JPTravel::Cost cost;
    cost.x = { 250, xAcceleration };
    cost.y = { 250, yAcceleration };
    for (int t = 2, scale = 100; scale > 0; t--, scale /= 10) {
        JPJavaRandom rnd(42);
        std::vector<JPLocation> list;
        // Some random places all over.
        for (int i = 0; i < 1 * scale + 10; i++) {
            const double x = rnd.nextDouble() * 1000.0, y = rnd.nextDouble() * 500.0, z = rnd.nextDouble() * 20.0;
            list.push_back(mm(x, y, z));
        }
        // X-aligned rows of feeders.
        for (int i = 0; i < 3 * scale; i++) {
            const double x = std::floor(rnd.nextDouble() * 5.0) * 250.0 + rnd.nextDouble() * 20.0;
            const double y = rnd.nextDouble() * 500.0, z = rnd.nextDouble() * 10.0;
            list.push_back(mm(x, y, z));
        }
        // Y-aligned rows of feeders.
        for (int i = 0; i < 2 * scale; i++) {
            const double x = rnd.nextDouble() * 1000.0;
            const double y = std::floor(rnd.nextDouble() * 2.0) * 500.0 + rnd.nextDouble() * 20.0, z = rnd.nextDouble() * 10.0;
            list.push_back(mm(x, y, z));
        }
        JPTravel tsm(list, mm(0, 0, 0), t == 1 ? std::optional(mm(0, 0, 0)) : t == 0 ? std::optional(mm(1000, 500, 0)) : std::nullopt, cost);
        const double leastCost = tsm.solve();
        // Driven by time; checked by the route's straight-line length.
        tsm.setCost(std::nullopt);
        const double linearDistance = tsm.travellingDistance();
        const double target = targets[t];
        std::fprintf(stderr, "test %s%d solved %zu locations, cost %.3f s, distance %.1f mm, target %.0f mm\n", name, t, list.size(),
                     leastCost, linearDistance, target);
        assert(linearDistance <= target * 1.01 && linearDistance >= target * 0.99);
    }
}

} // namespace

int main() {
    // A: slow acceleration; B: fast on X; C: fast on X and Y.
    const double a[] = { 2870, 5230, 11360 }, b[] = { 2940, 5550, 15300 }, c[] = { 2870, 5000, 11500 };
    test("A", 500, 500, a);
    test("B", 3000, 500, b);
    test("C", 3000, 3000, c);
    return 0;
}
